const data = {
  products: [
    {
      id: 1,
      name: 'apple',
      slug: 'apple14',
      category: 'mobile',
      img: '/img/app14.png',
      price: 55000000,
      countInStock: 2,
      brand: 'apple',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
      },
    {
      id: 2,
      name: 'apple',
      slug: 'apple',
      category: 'mobile',
      img: '/img/app14b.png',
      price: 75000000,
      countInStock: 2,
      brand: 'apple',
      rating: 4.0,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      id: 3,
      name: 'motorola',
      slug: 'motorola',
      category: 'mobile',
      img: '/img/motorz.png',
      price:10000000,
      countInStock: 5,
      brand: 'motorola',
      rating: 5.0,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      id: 4,
      name: 'motorola',
      slug: 'motorolaz',
      category: 'mobile',
      img: '/img/motorzb.png',
      price: 11000000,
      countInStock: 4,
      brand: 'motorola',
      rating: 3.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      id: 5,
      name: 'pixel',
      slug: 'pixel',
      category: 'mobile',
      img: '/img/pixel7.png',
      price: 15000000,
      countInStock: 2,
      brand: 'pixel',
      rating: 3.0,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      id: 6,
      name: 'pixel',
      slug: 'pixelp',
      category: 'mobile',
      img: '/img/pixel7b.png',
      price: 17000000,
      countInStock: 3,
      brand: 'pixel',
      rating: 5.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      id: 7,
      name: 'samsung',
      slug: 'samsung',
      category: 'mobile',
      img: '/img/samflip.png',
      price: 18000000,
      countInStock: 4,
      brand: 'samsung',
      rating: 2.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      id: 8,
      name: 'samsung',
      slug: 'samsungf',
      category: 'mobile',
      img: '/img/samflipb.png',
      price: 22000000,
      countInStock: 2,
      brand: 'samsung',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    
  ],
};

export default data
