import bcrypt from 'bcrypt'
const saltRounds = 12
const data = {
  user: [
    {
      name: 'user1',
      email: 'user1@gmail.com',
      password: await bcrypt.hash('user12345678', saltRounds),
      isAdmin: false,
    },
    {
      name: 'مدیر',
      email: 'admin@gmail.com',
      password: await bcrypt.hash('admin12345678', saltRounds),
      isAdmin: true,
    },
  ],
  products: [
    {
      // _id: 1,
      name: 'apple14',
      slug: 'apple14',
      category: 'mobile',
      img: '/img/app14.png',
      price: 55000000,
      countInStock: 3,
      brand: 'apple',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 2,
      name: 'apple14Pro',
      slug: 'apple14Pro',
      category: 'mobile',
      img: '/img/app14b.png',
      price: 55000000,
      countInStock: 2,
      brand: 'apple',
      rating: 4.0,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 3,
      name: 'motorolaz',
      slug: 'motorolaz',
      category: 'mobile',
      img: '/img/motorz.png',
      price: 10000000,
      countInStock: 5,
      brand: 'motorola',
      rating: 5.0,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 4,
      name: 'motorola1',
      slug: 'motorolaz1',
      category: 'mobile',
      img: '/img/motorzb.png',
      price: 11000000,
      countInStock: 4,
      brand: 'motorola',
      rating: 3.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 5,
      name: 'pixel',
      slug: 'pixel',
      category: 'mobile',
      img: '/img/pixel7.png',
      price: 15000000,
      countInStock: 2,
      brand: 'pixel',
      rating: 3.0,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 6,
      name: 'pixelp',
      slug: 'pixelp',
      category: 'mobile',
      img: '/img/pixel7b.png',
      price: 17000000,
      countInStock: 3,
      brand: 'pixel',
      rating: 5.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 7,
      name: 'samsungf',
      slug: 'samsungf',
      category: 'mobile',
      img: '/img/samflip.png',
      price: 18000000,
      countInStock: 4,
      brand: 'samsung',
      rating: 2.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 8,
      name: 'samsungp',
      slug: 'samsungp',
      category: 'mobile',
      img: '/img/samflipb.png',
      price: 22000000,
      countInStock: 2,
      brand: 'samsung',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 9,
      name: 'headbi1',
      slug: 'headbi1',
      category: 'headbi',
      img: '/img/h2.jpg',
      price: 22000000,
      countInStock: 2,
      brand: 'samsung',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 10,
      name: 'headbi3',
      slug: 'headbi3',
      category: 'headbi',
      img: '/img/h3.jpg',
      price: 22000000,
      countInStock: 2,
      brand: 'samsung',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 11,
      name: 'headbi4',
      slug: 'headbi4',
      category: 'headbi',
      img: '/img/h5.jpg',
      price: 22000000,
      countInStock: 2,
      brand: 'apple',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 12,
      name: 'headbi5',
      slug: 'headbi5',
      category: 'headbi',
      img: '/img/h3.jpg',
      price: 22000000,
      countInStock: 2,
      brand: 'motorola',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 13,
      name: 'headbi6',
      slug: 'headbi6',
      category: 'headbi',
      img: '/img/h3.jpg',
      price: 22000000,
      countInStock: 2,
      brand: 'motorola',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 14,
      name: 'headbi2',
      slug: 'headbi2',
      category: 'headba',
      img: '/img/h11.jpg',
      price: 22000000,
      countInStock: 2,
      brand: 'apple',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 15,
      name: 'headbi7',
      slug: 'headbi7',
      category: 'headba',
      img: '/img/h12.jpg',
      price: 22000000,
      countInStock: 2,
      brand: 'apple',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 16,
      name: 'headbi8',
      slug: 'headbi8',
      category: 'headba',
      img: '/img/10.jpg',
      price: 22000000,
      countInStock: 2,
      brand: 'samsung',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 17,
      name: 'headbi9',
      slug: 'headbi9',
      category: 'headba',
      img: '/img/h4.jpg',
      price: 22000000,
      countInStock: 2,
      brand: 'motorola',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 18,
      name: 'labtab1',
      slug: 'labtab1',
      category: 'labtab',
      img: '/img/labwin.jpg',
      price: 22000000,
      countInStock: 2,
      brand: 'apple',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 19,
      name: 'labtab2',
      slug: 'labtab2',
      category: 'labtab',
      img: '/img/labap.png',
      price: 22000000,
      countInStock: 2,
      brand: 'asus',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 19,
      name: 'labtab3',
      slug: 'labtab3',
      category: 'labtab',
      img: '/img/labtab1.png',
      price: 22000000,
      countInStock: 2,
      brand: 'samsung',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 19,
      name: 'flash1',
      slug: 'flash1',
      category: 'flash',
      img: '/img/flash1.jpg',
      price: 22000000,
      countInStock: 2,
      brand: 'samsung',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 19,
      name: 'flash2',
      slug: 'flash2',
      category: 'flash',
      img: '/img/flash2.jpg',
      price: 22000000,
      countInStock: 2,
      brand: 'samsung',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 19,
      name: 'flash3',
      slug: 'flash3',
      category: 'flash',
      img: '/img/flash2.png',
      price: 22000000,
      countInStock: 2,
      brand: 'sandisk',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      // _id: 19,
      name: 'flash4',
      slug: 'flash4',
      category: 'flash',
      img: '/img/flash3.jpg',
      price: 22000000,
      countInStock: 2,
      brand: 'sandisk',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
  ],
};

export default data
