const data = {
  products: [
    {
      id: 1,
      name: 'appel',
      slug: 'appel',
      category: 'mobile',
      img: '/img/app14.png',
      price: 5000,
      countInStock: 10,
      brand: 'appel',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      id: 2,
      name: 'sam',
      slug: 'sam',
      category: 'mobile',
      img: '/img/app14b.png',
      price: 5000,
      countInStock: 10,
      brand: 'appel',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      id: 3,
      name: 'moto',
      slug: 'moto',
      category: 'mobile',
      img: '/img/motorz.png',
      price: 5000,
      countInStock: 10,
      brand: 'motorala',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      id: 4,
      name: 'moto',
      slug: 'moto',
      category: 'mobile',
      img: '/img/motorzb.png',
      price: 5000,
      countInStock: 10,
      brand: 'motorala',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      id: 5,
      name: 'appel',
      slug: 'appel',
      category: 'mobile',
      img: '/img/pixel7.png',
      price: 5000,
      countInStock: 10,
      brand: 'appel',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      id: 6,
      name: 'sam',
      slug: 'sam',
      category: 'mobile',
      img: '/img/pixel7b.png',
      price: 5000,
      countInStock: 10,
      brand: 'appel',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      id: 7,
      name: 'moto',
      slug: 'moto',
      category: 'mobile',
      img: '/img/samflip.png',
      price: 5000,
      countInStock: 10,
      brand: 'motorala',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
    {
      id: 8,
      name: 'moto',
      slug: 'moto',
      category: 'mobile',
      img: '/img/samflipb.png',
      price: 5000,
      countInStock: 10,
      brand: 'motorala',
      rating: 4.5,
      numReviews: 5,
      description: 'hight quality',
    },
  ],
};

export default data
